### ISSUE TITLE
input text on media_player.alexa_tts

### ISSUE THREAD

**Issue by vMeph** [keatontaylor/custom_components#1]
would it be possible to add to the media_player.alexa_tts option to have a input text for alexa to speack the input text directly on the media player?

**Comment by keatontaylor** [comment]
So you're saying something like this? 

```
automation:
  - alias:
    trigger:
      platform: state
      entity_id: sensor.some_sensor
      to: 'on'
    action:
      service: media_player.alexa_tts
      data_template:
        entity_id: media_player.car_echo_dot
        message: {{ input_text.some_input_text_entity }}
```

If so, this is already supported.
