### ISSUE TITLE
timing issue? 

### ISSUE THREAD

**Issue by h4nc** [keatontaylor/custom_components#106]
Why does this work reliable: (with a script)

```
- alias: Alexa Routinen outdoor temp Netatmo
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.alexa_routine_outdoortemp
    to: 'on'
  action:
    - service: alexa_media.update_last_called  
    - delay: "00:00:01"
    - service: homeassistant.turn_on
      entity_id: script.alexa_routine_outdoortemp
    - service: homeassistant.turn_off
      entity_id: input_boolean.alexa_routine_outdoortemp
```
with script.yaml

```
alexa_routine_outdoortemp:
  sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: '{{ states.sensor.last_alexa.state }}' 
        volume_level: 0.3
    - delay:
        seconds: 0.5        
    - service: media_player.alexa_tts
      data_template:
        entity_id: '{{ states.sensor.last_alexa.state }}'
        message: "Die Außentemperatur beträgt {{ states.sensor.netatmo_temperature.state|round(0) }} grad Celsius"
```
and this one works from time to time

```
- alias: Alexa Routinen outdoortemp Netatmo
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.alexa_routine_outdoortemp
    to: 'on'
  action:
    - service: alexa_media.update_last_called  
    - delay: "00:00:01"
    - service: media_player.volume_set
      data_template:
        entity_id: '{{ states.sensor.last_alexa.state }}' 
        volume_level: 0.3
    - delay:
        seconds: 0.5        
    - service: media_player.alexa_tts
      data_template:
        entity_id: '{{ states.sensor.last_alexa.state }}'
        message: "Die Außentemperatur beträgt {{ states.sensor.netatmo_temperature.state|round(0) }} grad Celsius"
    - service: homeassistant.turn_off
      entity_id: input_boolean.alexa_routine_outdoortemp
```

alexa won’t talk, the volume is set to 0.3 (leds show up) but no talking.

Putting those line in a script and works
