### ISSUE TITLE
Alexa media_player component stays idle when playing playlists from spotify

### ISSUE THREAD

**Issue by RomRider** [keatontaylor/custom_components#41]
Hi,

When I run a spotify **playlist** in my HA automation for example, the `media_player.echo_plus_bathroom` stays in state `standby` in HA even though music is correctly playing. If I say `alexa play chillout lounge on spotify` the same happens, no feedback on HA.

```yaml
- service: media_player.play_media
   data:
        entity_id: media_player.echo_plus_bathroom
        media_content_id: Chillout Lounge
        media_content_type: SPOTIFY
```

It only happens for playlists apparently, and the Alexa App on my phone doesn't get feedback either. I'm running this in France
