### ISSUE TITLE
AttributeError: module 'custom_components.alexa_media' has no attribute 'setup'

### ISSUE THREAD

**Issue by hairychris** [keatontaylor/custom_components#93]
````
Error during setup of component alexa_media
````

When I start the component since upgrading to 0.88 it throws an error. It was working fine on 0.87. I have tried adjusting the file structure and replacing the files with version 1.0.0

File structure:

````
/appdata/homeassistant/custom_components/alexa_media
├── __init__.py
├── __pycache__
│   └── __init__.cpython-37.pyc
├── const.py
└── media_player.py
````

Configuration:

````
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: "amazon.co.uk"
````

Is anyone else seeing this? Is it something I am doing wrong or a bug?
